name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_release:
    strategy:
      matrix:
        os: [macOS-latest]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: build
        run: make release_mac

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: '*.zip'
